---
- name: Deploy Docker Container
  hosts: worker
  become: yes

  tasks:

    - name: Remove old container
      docker_container:
        name: myapp
        state: absent
      ignore_errors: yes

    - name: Remove old image
      docker_image:
        name: madhav7022/spring_project2003
        tag: v1
        state: absent
      ignore_errors: yes

    - name: Pull latest image
      docker_image:
        name: madhav7022/spring_project2003
        tag: v1
        source: pull

    - name: Run new container
      docker_container:
        name: myapp
        image: madhav7022/spring_project2003:v1
        state: started
        ports:
          - "8085:8085"
